Algoritmo "ex10"
// Autor (a): Samira
// Dados atuais: 25/08/2021
Var
num, fatorial, cont: inteiro

Inicio
escreval("ESSE PROGRAMA REVELA O FATORIAL DE NPUMEROS")
repita
fatorial<- 1
   escreval ("")
   escreval ("Digite um número:")
   leia (num)

   para cont de num ate 1 passo -1 faca

  fatorial <- fatorial * cont
   fimpara
escreval ("Fatorial de", num, " é: ", fatorial)

ate num = 0

Fimalgoritmo
