Algoritmo "ex2"
// Autor (a): Samira
// Dados atuais: 15/08/2021
Var
cont, resu, tab, final, prim: inteiro

Inicio
escreva ("Informe o número da tabuada que deseja ver:")
leia (tab)

escreval ("Você deseja fazer a tabuada até qual número ?:")
leia (final)

escreval ("Você quer começar a tabuada em qual número ?:")
leia (prim)

faca final para cont de prim ate

  resu <- (tab * cont)
  escreval (tab, "X", cont, "=", resu)

fimpara
Fimalgoritmo