Algoritmo "areatriangulo"
// Descrição   : calcular a area do triangulo
// Autor(a)    : Samira de Melo Oliveira
// Data atual  : 02/03/2021
Var
area, base, alt: real


Inicio

//entrada
escreval("Digite a base do triangulo retangulo")
leia(base)

escreval("Digite a altura do triangulo retangulo")
leia(alt)

//processamento
area <- (base*alt)/2

//saida
escreval("----------OBRIGADA!! TENHA UM ÓTIMO DIA----------")

Fimalgoritmo